# docker build rabbitMQ -t rabbitmq:v1
# docker run -d --hostname enved-rabbit --name rabbitmq -p 5672:5672 -p 15672:15672 rabbitmq:v1
FROM rabbitmq:3-management

# Define environment variables.
ENV default_user=user
ENV default_pass=pass
